name: "OpenALPR"
description: "My first real add-on!"
version: "1.0.0"
slug: "OpenALPR"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: ghcr.io/home-assistant/{arch}-base:latest