name: "Rotten Potatoes"
description: "My first real add-on!"
version: "1.0.0"
slug: "rotten_potatoes"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  6666/tcp: 6666
